version: '3.8'

services:
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/carbonos-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.scdc.cloud
    restart: always
    networks:
      - carbonos-network

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/carbonos-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://carbonos:carbonos@postgres:5432/carbonos
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - /lhcos-data:/app/uploads
    restart: always
    networks:
      - carbonos-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: carbonos
      POSTGRES_PASSWORD: carbonos
      POSTGRES_DB: carbonos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - carbonos-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U carbonos" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - carbonos-network
    restart: always

networks:
  carbonos-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
